### ISSUE TITLE
Executable directory

### ISSUE THREAD

**Issue by pulphix** [jenkinsci/wix-plugin#5]
Wix plugin is not reading properly the configuration setting.
This issue cause to fail because is not able to find executable.
The configuration used is:
C:\Program Files (x86)\WiX Toolset v3.9\bin
The Jenkins master is on linux machine but the job is executed in a jenkins node with windows installed

[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] No binary found: /C:\Program Files (x86)\WiX Toolset v3.9\bin/candle.exe

**Comment by rollinhand** [comment]
Thank you for filing the issue.
This is a known problem while creating the executable wrapper and the reason why the Wiki states "Please note that this plugin only works on Windows-driven Jenkins installations" (https://wiki.jenkins-ci.org/display/JENKINS/WIX+Toolset+Plugin). Currently this includes also the master.

I will add your issue for milestone 1.11 because 1.10 is still in testing and will be released soon.

**Comment by rollinhand** [comment]
Should be fixed with 1.10 released today. There was an issue with absolute paths the plugin used internally.

**Comment by pulphix** [comment]
Great thank you a lot.

**Comment by pulphix** [comment]
It still not working.
Current issue if you set the path on the configuration as
C:\Program Files (x86)\WiX Toolset v3.9\bin
Then the system builds the following path:
C:\Program Files (x86)\WiX Toolset v3.9\bin/candle.exe

If you set on the configuration:
C:\Program Files (x86)\WiX Toolset v3.9\bin\
Then I'm still getting the error:

[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] No binary found: C:\Program Files (x86)\WiX Toolset v3.9\bin\candle.exe

**Comment by rollinhand** [comment]
Have you tried to add WIX Toolset installation to PATH on Windows slave and leave installation path blank on global Wix toolset configuration as described in the Wiki?

The path C:\Program Files (x86)\WiX Toolset v3.9\bin/candle.exe should be no problem on a Windows machine because the operating system accepts / and \ as path separators.

I currently have no Unix master / Windows slave installation for verification. But it seems that the plugin searches on the master for the existence of the Wix installation - that's my guess...

I have reopened the issue...

**Comment by pulphix** [comment]
Do you have an estimation when this issue will be fixed?

**Comment by rollinhand** [comment]
Not yet. I can only try to remove the existence checks for candle.exe and light.exe.

**Comment by pulphix** [comment]
If you wanna provide me the jar before doing the release I can test it for you.

**Comment by rollinhand** [comment]
Great offer! Would appreciate if you could test it and give me feedback. I have added some fixes to the code and build a snapshot version.

You can find the HPI/JAR here: 
- https://dl.dropboxusercontent.com/u/105849591/wix.hpi
- https://dl.dropboxusercontent.com/u/105849591/wix.jar

**Comment by pulphix** [comment]
This is the error that I'm getting now
[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Wix Toolset plugin is running in slave mode.
[wix] Do not test if toolset is installed.
[wix] Starting compile process...
[wix] adding source file: D:\Jenkins\workspace\project\tools\wixtoolset\Installer.wxs
[wix] Executing command: "C:\Program Files (x86)\WiX Toolset v3.9\bin\candle.exe" -arch x86 -nologo -out "D:\Jenkins\workspace\project\tools\wixtoolset\Installer.wixobj" "D:\Jenkins\workspace\project\tools\wixtoolset\Installer.wxs" 
[wix] Cannot run program ""C:\Program": error=2, No such file or directory

**Comment by rollinhand** [comment]
Looks like the command is not executed on the slave but on master.

**Comment by rollinhand** [comment]
I have provided a new hpi and jar which uses the internal Hudson Launcher to call the commands. Can you test again?

**Comment by pulphix** [comment]
Absolutely.
Always ready to help.

**Comment by pulphix** [comment]
I think is missing the object file parameter on the light.exe command

[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Wix Toolset plugin is running in slave mode.
[wix] Do not test if toolset is installed.
[wix] Starting compile process...
[wix] adding source file: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
[wix] Executing command: "C:\Program Files (x86)\WiX Toolset v3.9\bin\candle.exe" -arch x86 -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
[project-win-0.70.0-ti] $ "C:\Program Files (x86)\WiX Toolset v3.9\bin\candle.exe" -arch x86 -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
project_Installer.wxs
[wix] Compiling successful.
[wix] Linking to file: D:\Jenkins\workspace\project-win-0.70.0-ti\setup.msi
[wix] no valid object file: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj
[wix] Executing command: "C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\setup.msi
[project-win-0.70.0-ti] $ "C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\setup.msi
 usage:  light.exe [-?] [-b bindPath] [-nologo] [-out outputFile] objectFile [objectFile ...] [@responseFile]

**Comment by rollinhand** [comment]
Your right, the command is missing the created wixobj file as input. The log is telling us "[wix] no valid object file: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj".

Is the object file created? Before light is started, it checks the presence of the object files. It is the same routine like for the source files - only file ending is changed.

**Comment by pulphix** [comment]
Yes,
I tried to to it by shell and it works.
So the parameter is missing.
A cool adding will be having a parameter to decide where to create the setup.msi file so that I'm able to change the name of it.

**Comment by rollinhand** [comment]
Well, interesting that it does not find the object file. I will remove the existence check. Maybe it does not work correctly on a remote node.

You can change the name of the setup.msi - as well as the path. You have to open the Advanced settings of the build step.

**Comment by pulphix** [comment]
It's not that he cannot find it it's more that on the call is not calling with the object as parameter

**Comment by rollinhand** [comment]
If isValid() fails with it checks it does not add the object file to the construction of the light command. So you will always miss the object file as parameter.

I have uploaded a new hpi and jar to Dropbox with more logging to see whats happening at this special part. Maybe I broke something or missing something by constructing a remote file path.

I have tested it today in the morning with our local system (no slave) and there it works... Let's find out what it is with this slaves...

**Comment by pulphix** [comment]
Let me know when is ready to test

**Comment by rollinhand** [comment]
Okay, new versions uploaded to Dropbox.

**Comment by pulphix** [comment]
can you provide me the urls?

**Comment by rollinhand** [comment]
The same as before:
https://dl.dropboxusercontent.com/u/105849591/wix.hpi
https://dl.dropboxusercontent.com/u/105849591/wix.jar

**Comment by pulphix** [comment]
I think he checks local jenkins not on the node:

[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Wix Toolset plugin is running in slave mode.
[wix] Do not test if toolset is installed.
[wix] Starting compile process...
[wix] isValid: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
[wix] isValid: true
[wix] adding source file: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
[wix] Executing command: "C:\Program Files (x86)\WiX Toolset v3.9\bin\candle.exe" -arch x86 -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
[project-win-0.70.0-ti] $ "C:\Program Files (x86)\WiX Toolset v3.9\bin\candle.exe" -arch x86 -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wxs
project_Installer.wxs
[wix] Compiling successful.
[wix] Linking to file: D:\Jenkins\workspace\project-win-0.70.0-ti\build\production\project\win\project.msi
[wix] isValid: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj
[wix] isValid: false
[wix] no valid object file: D:\Jenkins\workspace\project-win-0.70.0-ti\tools\wixtoolset\project_Installer.wixobj
[wix] Executing command: "C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\build\production\project\win\project.msi
[project-win-0.70.0-ti] $ "C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -nologo -out D:\Jenkins\workspace\project-win-0.70.0-ti\build\production\project\win\project.msi

**Comment by rollinhand** [comment]
Exactly what I expected. Fixed this part and created a new version - ready to test. Hopefully everything is fixed now:
- https://dl.dropboxusercontent.com/u/105849591/wix.hpi
- https://dl.dropboxusercontent.com/u/105849591/wix.jar

**Comment by pulphix** [comment]
Working fine now

**Comment by rollinhand** [comment]
Great stuff. I will release 1.11 tonight.
